export default {
    logo: '商城后台系统',
    topBar:{
        activeIndex:'0',
        list:[
            {
                name:'首页',
                subActive:'0',
                subMenu:[
                    {
                        title:'后台首页',
                        icon:'el-icon-menu',
                        pathname:'index'
                    },
                    {
                        title:'商品列表',
                        icon:'el-icon-s-goods',
                        pathname:'shop_goods_list'
                    },
                    {
                        title:'相册管理',
                        icon:'el-icon-picture',
                        pathname:'image'
                    },
                ]
            },
            {
                name:'商品',
                subActive:'0',
                subMenu:[
                    {
                        title:'商品列表',
                        icon:'el-icon-menu'
                    }
                ]
            },
            {
                name:'订单',
                subActive:'0',
            },
            {
                name:'会员',
                subActive:'0',
            },
            {
                name:'设置',
                subActive:'0',
            },
        ]
    }
}
